CREATE DATABASE COMPUTADORAS
CREATE TABLE COMPUTADORA (
IDPC INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
DESCRIPCION NVARCHAR (50) NOT NULL,
PRECIO MONEY NOT NULL,
CI NVARCHAR (10) NOT NULL,
FECHA DATETIME NOT NULL,
PRIMARY KEY (IDPC),
);